version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build the image
          command: docker build -t nodejs-dev .
